-- Accounting layer: roles + activity logs + secure logging RPC + RLS
create extension if not exists pgcrypto;

-- 1) Role enum and hierarchy helpers
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role') THEN
    CREATE TYPE public.app_role AS ENUM ('user', 'editor', 'admin');
  END IF;
END$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'user_information'
      AND column_name = 'role'
      AND udt_name <> 'app_role'
  ) THEN
    ALTER TABLE public.user_information
      ALTER COLUMN role DROP DEFAULT,
      ALTER COLUMN role TYPE public.app_role USING
        CASE
          WHEN role IN ('user', 'editor', 'admin') THEN role::public.app_role
          ELSE 'user'::public.app_role
        END,
      ALTER COLUMN role SET DEFAULT 'user'::public.app_role;
  END IF;
END$$;

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS public.app_role
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (
      SELECT ui.role
      FROM public.user_information ui
      WHERE ui.auth_user_id::text = auth.uid()::text
      LIMIT 1
    ),
    'user'::public.app_role
  );
$$;

CREATE OR REPLACE FUNCTION public.role_at_least(required_role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE public.current_user_role()
    WHEN 'admin'::public.app_role THEN true
    WHEN 'editor'::public.app_role THEN required_role IN ('editor'::public.app_role, 'user'::public.app_role)
    WHEN 'user'::public.app_role THEN required_role = 'user'::public.app_role
    ELSE false
  END;
$$;

GRANT EXECUTE ON FUNCTION public.current_user_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.role_at_least(public.app_role) TO authenticated;

-- 2) Activity logs table
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  action TEXT NOT NULL CHECK (char_length(action) BETWEEN 1 AND 120),
  resource TEXT NULL CHECK (resource IS NULL OR char_length(resource) <= 120),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'web' CHECK (char_length(source) <= 32),
  request_id UUID NOT NULL DEFAULT gen_random_uuid(),
  ip_address INET NULL,
  user_agent TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON public.activity_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id_created_at ON public.activity_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_action_created_at ON public.activity_logs (action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_metadata_gin ON public.activity_logs USING GIN (metadata jsonb_path_ops);

-- 3) Secure server-side logging function (prevents user_id spoofing)
CREATE OR REPLACE FUNCTION public.log_activity(
  p_action TEXT,
  p_resource TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_log_id BIGINT;
  v_headers JSONB;
  v_ip INET;
  v_user_agent TEXT;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '28000';
  END IF;

  v_headers := COALESCE(current_setting('request.headers', true)::jsonb, '{}'::jsonb);
  v_ip := NULLIF(split_part(COALESCE(v_headers ->> 'x-forwarded-for', ''), ',', 1), '')::inet;
  v_user_agent := NULLIF(v_headers ->> 'user-agent', '');

  INSERT INTO public.activity_logs (
    user_id,
    action,
    resource,
    metadata,
    source,
    ip_address,
    user_agent
  ) VALUES (
    v_user_id,
    trim(p_action),
    NULLIF(trim(COALESCE(p_resource, '')), ''),
    COALESCE(p_metadata, '{}'::jsonb),
    'web',
    v_ip,
    v_user_agent
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.log_activity(TEXT, TEXT, JSONB) TO authenticated;

-- 4) RLS for activity_logs
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS activity_logs_insert_own ON public.activity_logs;
DROP POLICY IF EXISTS activity_logs_select_own ON public.activity_logs;
DROP POLICY IF EXISTS activity_logs_select_editor ON public.activity_logs;
DROP POLICY IF EXISTS activity_logs_all_admin ON public.activity_logs;

-- user: can insert/select only own logs
CREATE POLICY activity_logs_insert_own
ON public.activity_logs
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY activity_logs_select_own
ON public.activity_logs
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- editor: can read all logs for monitoring
CREATE POLICY activity_logs_select_editor
ON public.activity_logs
FOR SELECT
TO authenticated
USING (public.role_at_least('editor'::public.app_role));

-- admin: full access
CREATE POLICY activity_logs_all_admin
ON public.activity_logs
FOR ALL
TO authenticated
USING (public.role_at_least('admin'::public.app_role))
WITH CHECK (public.role_at_least('admin'::public.app_role));
