create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'app_role'
      and typnamespace = 'public'::regnamespace
  ) then
    create type public.app_role as enum ('user', 'editor', 'admin');
  end if;
end
$$;

-- The original production tables predate this repository's migration history.
-- Recreate their initial shape so a clean local database can replay all later migrations.
create table if not exists public.user_information (
  user_id text not null,
  email varchar,
  created_at timestamptz not null default now(),
  auth_user_id text primary key,
  role public.app_role default 'user'::public.app_role
);

create table if not exists public.evaluations (
  id bigint generated by default as identity primary key,
  order_number text not null,
  subject_name text not null,
  overall_suggestion text,
  rubric jsonb,
  created_at timestamptz not null default now()
);
